services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - evasim_network

networks:
  evasim_network:
    driver: bridge